### ISSUE TITLE
Requests and suggestions:  python library is wanted. 

### ISSUE THREAD

**Issue by Goosina** [nekobean/mahjong-cpp#2]
Thanks for sharing such excellent work!
I would like to do more analysis using your work. But I don't know anything about cpp. 
I am wondering if you have any plans to provide a python library based on this project. 
Or can you tell me what tool can do to compile your project into python library? Maybe I can do it myself.
It would be my pleasure to get your reply!

**Comment by nekobean** [comment]
Thank you for your interest in my repository.
I will prioritize fixing known bugs, but hope to support Python Interface in the future.

There is a simillar library "mahjong" which supports shanten calculation and scoring.

[mahjong · PyPI](https://pypi.org/project/mahjong/)

**Comment by Goosina** [comment]
Thanks very much!
