### ISSUE TITLE
cmake 後の make コマンドについて

### ISSUE THREAD

**Issue by destagia** [nekobean/mahjong-cpp#22]
こちらのライブラリを使用したく、手元でビルドしてみたのですが、ビルド手順に記載されている `make -j` の手順にて Makefile が存在せずビルド手順を進められなくなりました。

Docker コンテナではなく、Windows上でビルドしています。

**Comment by nekobean** [comment]
make コマンドを使用する方法は Linux のビルド手順になります。
Windows の場合、[CMake](https://cmake.org/download/) を使用してプロジェクトファイルを作成したあと、Visual Studio などのコンパイラでビルドできます。
不明な点がありましたら、補足いたします。
