### ISSUE TITLE
Some errors faced using Windows

### ISSUE THREAD

**Issue by elvismtw** [nekobean/mahjong-cpp#4]
These are some errors I faced using Windows, here are some solutions I found online and I hope you find them helpful.

# cmake ..
This gives the following error.
CMake Error at CMakeLists.txt:3 (project):
```
  Running

   'nmake' '-?'

  failed with:

   The system cannot find the file specified
```

1. If you have g++ installed, add these two line at the top of CMakeLists.txt in the root directory
```
set( CMAKE_CXX_COMPILER "C:/MinGW/bin/g++.exe" )
set( CMAKE_C_COMPILER "C:/MinGW/bin/gcc.exe" )
```

2. Use ```cmake .. -G "MinGW Makefiles"```

# build
Building server gives the following error.
```
undefined reference to `__imp_WSAStartup'
```
1. add the following line in src/server/CMakeLists.txt below ```add_executable(server ${SRC_FILES} server.cpp)```
```
target_link_libraries(server PRIVATE ${Boost_LIBRARIES} spdlog ${CMAKE_DL_LIBS} ws2_32)
```
Also delete other target_link_libraries (next two lines).

Now clear the build directory and build again

**Comment by nekobean** [comment]
Thank you for sharing how to build with MinGW.
On Windows, I have confirmed it can be built with Visual Studio 2019 and 2022.
