### ISSUE TITLE
feature request: portable library usage

### ISSUE THREAD

**Issue by Equim-chan** [nekobean/mahjong-cpp#7]
Hi, I'm the developer of [Mortal](https://github.com/Equim-chan/Mortal), an open source mahjong AI. I've been looking for a way to properly integrate mahjong-cpp into Mortal because, for a long time, Mortal, more specifically the underlying [libriichi](https://github.com/Equim-chan/Mortal/tree/main/libriichi), lacked such a hand searching mechanism, potentially resulting in a performance bottleneck. Here's my thoughts about this:

## 1. Use over C FFI
I found suitable interfaces in `src/mahjong/json_parser.cpp`. `create_draw_response` and `create_discard_response` are ideal for my usage, and structs like `RequestData` are well-defined. However, bridging Rust and C++ is a bit challenging and requires extensive revisions, including rewriting C++ struct in C (no more use of `std::vector<double>`) and creating a Rust wrapper for the C interface.

## 2. Rewrite in Rust
Although this was actually my first thought, I checked `src/mahjong/expectedvaluecalculator.cpp` and found it difficult due to the complexity of it. Additionally, the code structure of it is so different from libriichi that some glue code will need to be added, making this option no less burdensome.

## 3. Use over HTTP (server.cpp)
This is the most portable option, but may be less reliable or efficient. It would definitely make deployment and maintenance of Mortal-based applications harder as it introduces another dependency process.

How do you think of these options and do you have other suggestions? Thank you for this great work.

**Comment by nekobean** [comment]
Thank you for your interest in this repository.
mahjong-cpp has an interface for input/output in JSON string. It is used for the web application "何切るシミュレーター" (https://pystyle.info/apps/mahjong-nanikiru-simulator/)

I am not familiar with Rust. If the following function exists, can it be easily ported to Rust?

```
std::string calc_exp_value(std::string request);
```

**Comment by Equim-chan** [comment]
Yes that would be easier.

**Comment by Equim-chan** [comment]
I tried to translate the structs in json_parser.hpp into C. Note that this is not tested yet.

```c

struct MeldedBlock {
    uint8_t type;
    size_t tils_size;
    uint8_t *tiles;
    uint8_t discarded_tile;
    uint8_t from;
}

struct RequestData {
    uint8_t zikaze;
    uint8_t bakaze;
    uint8_t turn;

    size_t dora_indicators_size;
    uint8_t *dora_indicators;

    size_t handle_tiles_size;
    uint8_t *handle_tiles;

    size_t melded_blocks_size;
    struct MeldedBlock *melded_blocks;

    uint8_t flag;
    uint8_t counts[37];
};

struct DrawResponseData {
    size_t time_us;

    size_t required_tiles_size;
    uint8_t (*required_tiles)[2];

    size_t tenpai_probs_size;
    double tenpai_probs;

    size_t win_probs_size;
    double win_probs;

    size_t exp_values_size;
    double exp_values;
};

struct Candidate {
    uint8_t tile;

    /*! 巡目ごとの聴牌確率 */
    size_t tenpai_probs_size;
    double *tenpai_probs;

    /*! 巡目ごとの和了確率 */
    size_t win_probs_size;
    double *win_probs;

    /*! 巡目ごとの期待値 */
    size_t exp_values_size;
    double *exp_values;

    /*! 有効牌及び枚数の一覧 */
    size_t required_tiles_size;
    uint8_t (*required_tiles)[2];

    /*! 向聴戻しになるかどうか */
    bool syanten_down;
};

struct DiscardResponseData {
    size_t time_us;
    size_t candidates_size;
    struct Candidate *candidates;
};
```

**Comment by nekobean** [comment]
I will create an API that interacts in JSON or struct commented above.
I hadn't updated the code in almost 2 years, so please give me a week to recall.

**Comment by Equim-chan** [comment]
I actually tried rewriting it in Rust and it worked like a charm, turns out it was not as difficult as I thought. I will release the Rust port in the upcoming release of Mortal.

Since my initial problem is resolved, I think this issue can be closed now.

**Comment by nekobean** [comment]
Sorry for the late reply.
I haven't logged in to GitHub for a while.
Glad to hear the problem was solved.
